### ISSUE TITLE
windows context fields are grayed out. 

### ISSUE THREAD

**Issue by dwischmeyer** [rosshadden/sublime-xpath#18]
On a fresh install of either ST2 or ST3 when adding this plugin the windows context fields are grayed out and inaccessible. Any ideas? Console dump below. Let me know if anything else would be helpful.

P.S. I have not looked at this since Ross originally developed it for us, excellent additions we appreciate it. 

DPI scale: 1
startup, version: 3103 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/PBlessing.ASI/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/PBlessing.ASI/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/PBlessing.ASI/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 1.15434
startup time: 1.20034
first paint time: 1.20034
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin sublime-xpath.lxml_parser
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\PBlessing.ASI\AppData\Roaming\Sublime Text 3\Packages\sublime-xpath\lxml_parser.py", line 1, in <module>
    from lxml.sax import ElementTreeContentHandler
ImportError: No module named 'lxml'
reloading plugin sublime-xpath.sublime_helper
reloading plugin sublime-xpath.sublime_input
reloading plugin sublime-xpath.sublime_input_quickpanel
reloading plugin sublime-xpath.sublime_input_view
reloading plugin sublime-xpath.sublime_lxml
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\PBlessing.ASI\AppData\Roaming\Sublime Text 3\Packages\sublime-xpath\sublime_lxml.py", line 2, in <module>
    from .lxml_parser import *
  File "C:\Users\PBlessing.ASI\AppData\Roaming\Sublime Text 3\Packages\sublime-xpath\lxml_parser.py", line 1, in <module>
    from lxml.sax import ElementTreeContentHandler
ImportError: No module named 'lxml'
reloading plugin sublime-xpath.tests
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\PBlessing.ASI\AppData\Roaming\Sublime Text 3\Packages\sublime-xpath\tests.py", line 4, in <module>
    from .lxml_parser import *
  File "C:\Users\PBlessing.ASI\AppData\Roaming\Sublime Text 3\Packages\sublime-xpath\lxml_parser.py", line 1, in <module>
    from lxml.sax import ElementTreeContentHandler
ImportError: No module named 'lxml'
reloading plugin sublime-xpath.xpath
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\PBlessing.ASI\AppData\Roaming\Sublime Text 3\Packages\sublime-xpath\xpath.py", line 4, in <module>
    from lxml import etree
ImportError: No module named 'lxml'
reloading plugin sublimetext_indentxml.indentxml
plugins loaded

**Comment by keith-hall** [comment]
It seems that the `lxml` dependency isn't loading properly. I can't see anything relating to Package Control in that console log dump, so I'm guessing you installed this plugin manually? Not a problem, but you will need to also install the `lxml` package from https://github.com/eerohele/sublime-lxml manually, as ST3 doesn't come bundled with it.

**Comment by keith-hall** [comment]
To install `lxml` manually, all you need to do is:
- visit the link in my previous post
- click the `Download  ZIP` button on the top right
- from Sublime Text, go to the `Preferences` menu -> `Browse Packages...`, which will open up the packages folder
- extract the zip file you downloaded to this folder
- rename the folder `sublime-lxml-master` to `lxml`
- restart Sublime Text

hopefully that should fix it :)

**Comment by dwischmeyer** [comment]
Ahhh, you are correct, we just did a direct pull. I will have them grab it through the package manager and try that out.

Thanks for the quick response, I appreciate what you have done with the package.


Thanks

D.j.


D.j. Wischmeyer, ACE | Operations and Support Manager
IVANS Insurance Solutions, a division of Applied Systems, Inc.
www.ivansinsurance.com<http://www.ivansinsurance.com/> | dwischmeyer@ivansinsurance.com<mailto:dwischmeyer@ivansinsurance.com>
P: 513.943.0000 ext. 33704

This message is for the designated recipient only and may contain confidential, proprietary, or
otherwise private information. If you have received this message in error, please notify the sender
immediately and delete the original.  Any other use or distribution of this information is prohibited.

**Comment by dwischmeyer** [comment]
Keith,

I had them pull it through the packager and it worked like a charm. Thanks for taking a look at this I appreciate it.

Thanks

D.j.


D.j. Wischmeyer, ACE | Operations and Support Manager
IVANS Insurance Solutions, a division of Applied Systems, Inc.
www.ivansinsurance.com<http://www.ivansinsurance.com/> | dwischmeyer@ivansinsurance.com<mailto:dwischmeyer@ivansinsurance.com>
P: 513.943.0000 ext. 33704

This message is for the designated recipient only and may contain confidential, proprietary, or
otherwise private information. If you have received this message in error, please notify the sender
immediately and delete the original.  Any other use or distribution of this information is prohibited.

**Comment by keith-hall** [comment]
Super, you are very welcome - glad it all got sorted :)
