### ISSUE TITLE
"ImportError: DLL load failed: The specified module could not be found." On Install

### ISSUE THREAD

**Issue by EmileSonneveld** [rosshadden/sublime-xpath#30]
When installing the plugin  (via the package manager), I get the following error in the console:

> ignored packages updated to: ["Vintage", "xpath"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin xpath.lxml_parser
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lxml_parser in C:\Users\emilesonneveld\AppData\Roaming\Sublime Text 3\Installed Packages\xpath.sublime-package", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
reloading plugin xpath.sublime_helper
reloading plugin xpath.sublime_input
reloading plugin xpath.sublime_input_quickpanel
reloading plugin xpath.sublime_input_view
reloading plugin xpath.sublime_lxml
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "sublime_lxml in C:\Users\emilesonneveld\AppData\Roaming\Sublime Text 3\Installed Packages\xpath.sublime-package", line 2, in <module>
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lxml_parser in C:\Users\emilesonneveld\AppData\Roaming\Sublime Text 3\Installed Packages\xpath.sublime-package", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
reloading plugin xpath.tests
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "tests in C:\Users\emilesonneveld\AppData\Roaming\Sublime Text 3\Installed Packages\xpath.sublime-package", line 6, in <module>
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lxml_parser in C:\Users\emilesonneveld\AppData\Roaming\Sublime Text 3\Installed Packages\xpath.sublime-package", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
reloading plugin xpath.xpath
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "xpath in C:\Users\emilesonneveld\AppData\Roaming\Sublime Text 3\Installed Packages\xpath.sublime-package", line 4, in <module>
ImportError: DLL load failed: The specified module could not be found.
reloading settings Packages/xpath/xpath.sublime-settings
generating syntax summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

And I can't find the commands with Ctrl-Shift-P. 
It used to work on my previous computer.

Is there any fix/workaround for this? Thanx!

Perhaps relevant:
Windows 10
Sublime text 3126
Visual studio 2015 is installed
python 3.6.1 is installed and added to path

**Comment by keith-hall** [comment]
Thanks for reporting, and sorry to hear you are having trouble.

Please can you execute the following in the ST Console (View menu -> Show Console) and let me know the output:

```python
sublime.arch(); import sys; sys.path
```

I suspect that maybe your Python 3.6 installation has the lxml package installed, and for some reason ST is finding that first, instead of the dependency that this xpath package uses. Because the Python versions (the one ST uses and the one you have installed) differ, it will report that the compiled module can't be found, when in fact it can - just the wrong one, because the module it found was compiled for a different Python version...

**Comment by EmileSonneveld** [comment]
Thanks for the fast response.
My output is:
> 'x32'
['C:\\Program Files (x86)\\Sublime Text 3', 'C:\\Program Files (x86)\\Sublime Text 3/python3.3.zip', 'C:\\Users\\emilesonneveld\\AppData\\Roaming\\Sublime Text 3\\Packages', 'C:\\Users\\EMILES~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\lxml\\ST3_WI~1']

**Comment by keith-hall** [comment]
Thanks for the info - it seems I'm wrong, the paths ST is using to load modules is fine, which is good news :+1:

---

Further investigation has revealed that maybe the [`sublime-lxml` dependency that xpath is using](https://github.com/eerohele/sublime-lxml) isn't [currently compatible with a 32 bit architecture, as someone else reported issues with it](https://github.com/eerohele/exalt/issues/3#issuecomment-269940989).

Is your Windows 10 installation 32 bit? Or are you able to switch to a 64 bit version of Sublime Text? Unfortunately I don't have a 32 bit installation of Windows or the experience of compiling C code on Windows to know how to build a working version of the `lxml` library for ST's Python 3.3, so switching to 64 bit ST is all I can really suggest at the moment. If you do switch, I'm not sure how Package Control would handle the dependency - you may need to uninstall this plugin, wait for the `sublime-lxml` package to get removed as well (check the console log to see when this happens), and then reinstall `xpath`, wait for `sublime-lxml` 64 bit to be installed (Package Control will say that a missing dependency was installed) and restart ST again.

**Comment by EmileSonneveld** [comment]
Dear god, everything works indeed find in 64bit. Thanks a lot! :)
Sometimes I install 32bit apps because they are slightly lighter. I guess it is not always the best choice.
