### ISSUE TITLE
Why am I getting ImportError even after successfully installation of scikit-learn?(sublime)

### ISSUE THREAD

**Issue by HinalVakharia** [rosshadden/sublime-xpath#42]
errror :
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\demo.py", line 1, in <module>
    from sklearn import tree
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\__init__.py", line 76, in <module>
    from .base import clone
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\base.py", line 16, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\__init__.py", line 13, in <module>
    from scipy.sparse import issparse
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\sparse\__init__.py", line 230, in <module>
    from .csr import *
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\sparse\csr.py", line 13, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: DLL load failed: The specified module could not be found.
[Finished in 1.6s]

**Comment by keith-hall** [comment]
Hi, the steps you are executing and the error you are getting appear to be unrelated to this plugin (XPath functions for XML files in Sublime Text), perhaps you meant to post this on a different repository's issue tracker (like one for a Scikit-learn package?)
